# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

pr:
  autoCancel: true

pool:
  vmImage: "windows-2019"

steps:
  - checkout: self
    displayName: "Checkout repository"

  - task: PowerShell@2
    name: ResourcesJSON
    displayName: "Generating Resources JSON from PSGallery"
    inputs:
      filePath: "./Get-DscResourceKitInfo.ps1"
      pwsh: true
      errorActionPreference: continue

  - task: MrCSharp.hugo-build-task-azure-devops.hugo-build-task.hugo-build-task@1
    displayName: "Generate Hugo site"
    inputs:
      destination: "$(Build.ArtifactStagingDirectory)"
      hugoVersion: 0.135.0

  - task: PublishPipelineArtifact@0
    displayName: "Publish Hugo site as artifact"
    inputs:
      artifactName: "dsccommunity"
      targetPath: "$(Build.ArtifactStagingDirectory)"
